spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/eomcal
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800 #30분

logging.level:
  org.hibernate.SQL: debug
